
'''
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

from projectEuler import solveIntegerQuadratic, isTriangle, isPentagonal,isHexagonal
from PE_sequences import iPentagonal, iHexagonal, iTriangle


def problem45():
	# We go over all hexagonals as it is the sequence that increases the most
	record = 40755
	for t in iHexagonal():
		if t > record and isTriangle(t) and isPentagonal(t):
			return t

from cProfile import run
if __name__ == "__main__":
	print(problem45() == 1533776805)
	run("problem45()")
