#!/usr/local/bin/python3.3

'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

'''

from PE_primes import sigma

def problem12():
	for n in range(8000,10000000):
		if n % 2 == 0:
			div = sigma(n//2,0)*sigma(n + 1,0)
		else:
			div = sigma(n,0)*sigma((n + 1)//2,0)
		if div > 500:
			return n*(n+1)//2	


from cProfile import run
if __name__ == "__main__":
	print(problem12())
	print(problem12() == 76576500)
	run("problem12()")